/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.tsx')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    LinkList: typeof import('./components/LinkList.vue')['default']
    Lorem: typeof import('./components/Lorem.vue')['default']
    Lorem2: typeof import('./components/Lorem2.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./components/Title.vue')['default']
  }
}
