/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.tsx')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IIconCarbonLogoGithub: typeof import('~icons/ic/on-carbon-logo-github')['default']
    Image: typeof import('./components/Image.vue')['default']
    ISimpleIconsTiddlywiki: typeof import('~icons/simple-icons/tiddlywiki')['default']
    ISimpleIconsVuejs: typeof import('~icons/simple-icons/vuejs')['default']
    ISimpleIconsVuejsDark: typeof import('~icons/simple-icons/vuejs-dark')['default']
    ISkillIconsVuejs: typeof import('~icons/skill-icons/vuejs')['default']
    ISkillIconsVuejsDark: typeof import('~icons/skill-icons/vuejs-dark')['default']
    ISkillIconsVuejsLight: typeof import('~icons/skill-icons/vuejs-light')['default']
    LinkList: typeof import('./components/LinkList.vue')['default']
    Lorem: typeof import('./components/Lorem.vue')['default']
    Lorem2: typeof import('./components/Lorem2.vue')['default']
    Md: typeof import('./components/Md.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./components/Title.vue')['default']
  }
}
